<jsp:include page="include/header1.jsp"></jsp:include>   
	<div class="container" id="main-content content">
		<section>
			<div class="my-account">
				<h1>My Account</h1>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent fermentum non nulla nec fermentum. Maecenas feugiat a turpis sed dictum. Nullam consequat magna odio. Donec aliquam faucibus sapien, ac pretium quam bibendum eget. Donec ullamcorper vel lacus in suscipit. Aenean aliquet semper purus non accumsan. Ut sodales dapibus tempor. Fusce sit amet adipiscing nulla. Maecenas facilisis tellus ante. In eget odio aliquam, bibendum orci vel, molestie lorem. Nullam bibendum nunc condimentum, posuere ipsum euismod, congue enim. Maecenas nulla dui, venenatis non enim et, pulvinar vestibulum erat. Praesent justo elit, mollis aliquet pretium congue, accumsan non felis. Vivamus blandit porttitor dui sit amet ultrices.</p>
				<p>Curabitur bibendum suscipit auctor. Nulla vel viverra felis. Nullam eget quam ac sem accumsan porttitor a eu risus. Pellentesque quis tellus sit amet erat venenatis laoreet. Aenean vitae sem auctor eros rutrum consequat. Quisque eleifend, augue ac aliquet tempus, lacus ante vulputate quam, ut vestibulum erat velit vel magna. Suspendisse potenti. Mauris adipiscing sem nibh. Phasellus adipiscing, elit sollicitudin elementum vehicula, metus nulla interdum nibh, et malesuada mauris lectus ut felis.</p>
				<p>Donec ac molestie ligula, ut porttitor diam. Vivamus malesuada fringilla nulla, non viverra risus adipiscing nec. Donec vestibulum ligula ac dui mollis ultricies. Fusce fringilla leo nec enim pellentesque sagittis. Proin vitae urna quis diam facilisis vulputate. Integer vestibulum, massa in ultricies semper, lacus tellus elementum nibh, id gravida nibh turpis nec massa. Proin in odio fringilla, rhoncus dolor ac, imperdiet felis. Maecenas eleifend semper varius. Sed tincidunt lorem ut dignissim sodales. Phasellus in fringilla nisi, id interdum mauris. Curabitur mattis dignissim eleifend. Nulla facilisi. Pellentesque varius pretium elit sed ultrices. Phasellus commodo ultrices mattis. Sed rhoncus mauris et varius suscipit.</p>
				<p>Maecenas elementum, metus quis posuere commodo, diam libero vestibulum lacus, at consequat diam diam volutpat erat. Suspendisse gravida consectetur scelerisque. Nulla sit amet porta erat. Nullam consequat sapien ut elit convallis, sed vestibulum nisi dapibus. Nulla adipiscing metus magna, eget aliquet sem suscipit non. Sed ornare, nibh ac ultrices adipiscing, ligula risus ullamcorper elit, ac auctor turpis turpis non lorem. Mauris ornare odio eget ante suscipit blandit. Quisque fermentum iaculis risus.</p>
				<p>Suspendisse facilisis, lectus vitae sodales tempus, mauris tortor ullamcorper nisi, ut mattis lacus dolor non augue. Integer sit amet nisi eros. Vivamus adipiscing molestie eros id molestie. In at malesuada ante. Aenean a est sit amet erat viverra adipiscing. Nunc eu ipsum iaculis, varius diam et, fermentum ante. Nullam id lorem ut nisl gravida fermentum. Nam malesuada nisl ut risus scelerisque, quis convallis dolor convallis. Ut aliquet in urna sit amet tempor. Nulla lobortis nisi non enim iaculis, sit amet tristique felis dignissim. Ut in ligula a nisi ullamcorper vehicula. </p>
			</div>
		</section>
	</div>
<jsp:include page="include/footer.jsp"></jsp:include>