<jsp:include page="../include/header.jsp"></jsp:include>
	<div class="container" id="main-content">
		<section>
			<div class="group">
				<h1>How to Use</h1>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis et ante a est bibendum mollis. Etiam diam metus, tempor vitae velit ut, aliquet pretium enim. Maecenas sit amet mollis justo. Proin euismod nunc ut purus sollicitudin rhoncus. Morbi dignissim id orci ut pharetra. Nunc vitae felis vulputate, auctor turpis sit amet, ultricies dui. In facilisis lectus turpis, vel accumsan urna facilisis vitae. Nullam ut consectetur nunc. Donec et tincidunt urna. Curabitur adipiscing risus eget risus adipiscing porttitor. Donec malesuada lectus nibh, quis tristique tellus tempor nec.</p>
				<p>Integer ut mattis dui, at eleifend nisl. Nulla suscipit justo quam, id rutrum libero dignissim quis. Donec imperdiet enim sed dolor ullamcorper, et lobortis ipsum lobortis. Integer laoreet diam in felis interdum, id lacinia magna tincidunt. Curabitur dapibus est sem, vitae pellentesque mauris elementum sit amet. Curabitur euismod feugiat lectus, ac accumsan odio tempor quis. Nulla facilisi. In hac habitasse platea dictumst. Morbi massa magna, dapibus id nulla vel, ultricies euismod tellus. Aliquam faucibus orci a elit varius fermentum. Proin suscipit justo a elit porttitor, eu pellentesque nisl imperdiet. Vestibulum aliquet purus nunc, vitae dignissim sapien scelerisque a. Nam quis ante pretium, varius massa in, tempor felis.</p>
				<p>Nullam id diam quis elit convallis egestas. Aenean tincidunt arcu odio, in porta lacus ornare nec. Pellentesque in dui ultrices, eleifend elit id, dignissim magna. Ut vel mauris nec arcu varius ullamcorper. Curabitur pharetra, orci nec ullamcorper feugiat, sem urna luctus dui, ac aliquam ligula turpis sit amet tortor. Maecenas in leo posuere, volutpat arcu sed, ultrices metus. Etiam rutrum, sapien sed sollicitudin eleifend, nunc libero cursus libero, vitae imperdiet purus nulla et nisi. Vestibulum et ultricies felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at elit nisi. In fermentum in mauris vitae tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse mattis nisl ullamcorper, consectetur nulla egestas, facilisis risus.</p>
				<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris tristique, justo a sagittis pulvinar, dolor erat pulvinar dolor, ac ornare purus nisi et nisi. Aliquam at arcu felis. Vivamus enim turpis, volutpat quis dolor et, pharetra venenatis neque. Mauris blandit sed nisi vel scelerisque. Donec condimentum neque rhoncus, sagittis lacus iaculis, laoreet nunc. Proin nec justo vitae felis convallis iaculis sit amet eu lectus. Vestibulum vitae magna a arcu commodo faucibus at sed ipsum. Nunc blandit sapien nec mi dapibus faucibus. Cras laoreet, libero sed semper gravida, nibh lectus facilisis massa, ut adipiscing erat dolor a turpis.</p>
				<p>Etiam lobortis, arcu a consequat pulvinar, est dolor varius elit, at fringilla metus lacus nec ligula. Proin cursus, nulla cursus auctor iaculis, felis dui commodo eros, vel egestas sem sem vel felis. Cras posuere faucibus sagittis. Donec id dolor at eros tincidunt posuere ac id leo. Morbi rutrum et lectus nec pellentesque. Maecenas felis purus, auctor vel laoreet ac, malesuada sit amet risus. Donec blandit neque pharetra velit sollicitudin, id ornare nunc tempor. Donec dapibus placerat tellus bibendum tempus. Vivamus luctus tempus urna, vitae tristique dolor aliquam in. Vestibulum cursus massa augue, in elementum enim convallis id.</p> 
			</div>
			
		</section>
	</div>
	

<jsp:include page="../include/footer.jsp"></jsp:include>